name: test-tift-react-app
on: [push]
jobs: 
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./engine
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '17'
      - name: install typescript
        run: npm install -g typescript
      - name: install jest
        run: npm install -g jest
      - name: install engine dependencies
        run: npm install
        working-directory: ./engine
      - name: compile engine
        run: tsc
        working-directory: ./engine
      - name: install web app
        run: npm install
        working-directory: ./react-app
      - name: test web app
        run: npm test -- --watchAll=false
        working-directory: ./react-app