name: test-tift-react-app
on: [push]
jobs: 
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./engine
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '17'
      - name: install type dependencies
        run: npm install
        working-directory: ./types
      - name: compile types
        run: npx tsc
        working-directory: ./types
      - name: install engine dependencies
        run: npm install
        working-directory: ./engine
      - name: compile engine
        run: npx tsc
        working-directory: ./engine
      - name: install web app
        run: npm install
        working-directory: ./react-app
      - name: test web app
        run: npm test -- --watchAll=false
        working-directory: ./react-app